name: unit-tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9.18, 3.10.13, 3.11.6, 3.12.1, 3.13.0]
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }} and UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with UV
        run: |
          uv pip install --upgrade pip
          uv pip install -r requirements.txt

      - name: Run unit tests
        run: uv python -m pytest tests/