name: Python Tests (macOS)

on:
  pull_request:
    branches: [requirements-tests]
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: macos-latest  # Cambio clave aquí

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest tests/ -v